---
###################################################################################################
# Docker: work helper definitions
###################################################################################################

agentic_help_software_enabled: []
agentic_help_software_available: {}
