---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: 🕛 Nightly tags


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Nightly: At 18:00 on Sunday, Tuesday, and Thursday
  schedule:
    - cron: '0 18 * * 0,2,4'
  # Dispatch: allows for manual trigger via GH UI
  workflow_dispatch:


jobs:

  # -----------------------------------------------------------------------------------------------
  # (1/6) Determine parameter settings
  # -----------------------------------------------------------------------------------------------
  params:
    uses: ./.github/workflows/params-nightly_tags.yml


  # -----------------------------------------------------------------------------------------------
  # (2/6) Configure Build and Deploy Matrices
  # -----------------------------------------------------------------------------------------------
  configure:
    needs: [params]
    uses: devilbox-community/github-actions/.github/workflows/docker-multistage-configure.yml@master
    with:
      enabled: true
      can_deploy: true
      versions: ${{ needs.params.outputs.versions }}
      refs: ${{ needs.params.outputs.refs }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}


  # -----------------------------------------------------------------------------------------------
  # (3/6) Build & Test base
  # -----------------------------------------------------------------------------------------------
  build-base:
    needs:
      - configure
    uses: devilbox-community/github-actions/.github/workflows/docker-multistage-build.yml@master
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      run_tests: false
      upload_artifact: true
      pull_base_image: true
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: base
      stage_prev: ''

  test-base:
    needs:
      - configure
      - build-base
    uses: devilbox-community/github-actions/.github/workflows/docker-multistage-test.yml@master
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: base


  # -----------------------------------------------------------------------------------------------
  # (4/6) Build & Test work
  # -----------------------------------------------------------------------------------------------
  build-work:
    needs:
      - configure
      - build-base
    uses: devilbox-community/github-actions/.github/workflows/docker-multistage-build.yml@master
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      run_tests: false
      upload_artifact: true
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: work
      stage_prev: base

  test-work:
    needs:
      - configure
      - build-work
    uses: devilbox-community/github-actions/.github/workflows/docker-multistage-test.yml@master
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: work


  # -----------------------------------------------------------------------------------------------
  # (5/6) Push images
  # -----------------------------------------------------------------------------------------------
  push-base:
    needs:
      - configure
      - test-base
      - test-work
    uses: devilbox-community/github-actions/.github/workflows/docker-multistage-push-image.yml@master
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: base
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  push-work:
    needs:
      - configure
      - test-base
      - test-work
    uses: devilbox-community/github-actions/.github/workflows/docker-multistage-push-image.yml@master
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: work
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}


  # -----------------------------------------------------------------------------------------------
  # (6/6) Push Manifests
  # -----------------------------------------------------------------------------------------------
  manifest-base:
    needs:
      - configure
      - push-base
    uses: devilbox-community/github-actions/.github/workflows/docker-multistage-push-manifest.yml@master
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_deploy }}
      versions: ${{ needs.configure.outputs.versions }}
      stage: base
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  manifest-work:
    needs:
      - configure
      - push-work
    uses: devilbox-community/github-actions/.github/workflows/docker-multistage-push-manifest.yml@master
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_deploy }}
      versions: ${{ needs.configure.outputs.versions }}
      stage: work
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
