---
name: build-work

on:
  workflow_dispatch:
  push:
    branches: [master, main]

jobs:
  build-work:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [latest, stable]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Generate Dockerfiles
        run: make gen
      - name: Build base image (parent)
        run: make build STAGE=base VERSION=${{ matrix.release }}
      - name: Build work image
        run: make build STAGE=work VERSION=${{ matrix.release }}
